# If you want to add a new currency, use this template:
#short_name = "Long name of the coin"

# Which can be expanded into:
#[coins.short_name]
#long_name = "Long name of the coin"
#bitfinex = "The name used for access on the Bitfinex API. Default: [short_name] in CAPSLOCK"
#coinmarketcap = "The name used for access on the CoinMarketCap API. Default: name in kebab-case"

# coinmarketcap can be expanded into:
#[coins.short_name.coinmarketcap]
#id = "The name used for access on the CoinMarketCap API. Default: [short_name.name] in kebab-case"
#conversion_symbol = "The symbol used for access on the CoinMarketCap API. Default: [short_name] in lowercase"

[coins]
# Fiat
usd = "U.S. Dollar"
eur = "Euro"
chf = "Swiss Franc"
aud = "Australian Dollar"
brl = "Brazilian Real"
cad = "Canadian Dollar"
clp = "Chilean Peso"
cny = "Chinese Yuan"
czk = "Czech Koruna"
dkk = "Danish Krone"
gbp = "Great British Pound"
hkd = "Hong Kong Dollar"
huf = "Hungarian Forint"
idr = "Indonesian Rupiah"
ils = "Israeli Shekel"
inr = "Indian Rupee"
jpn = "Japanese Yen"
krw = "South Korean Won"
mxn = "Mexican Peso"
myr = "Malaysian Ringgit"
nok = "Norwegian Krone"
nzd = "New Zealand Dollar"
php = "Philippine Peso"
pkr = "Pakistani Rupee"
pln = "Polish Zioty"
rub = "Russian Ruble"
sek = "Swedish Krona"
sgd = "Singapore Dollar"
thb = "Thai Baht"
try = "Turkish Lira"
twd = "Taiwan New Dollar"
zar = "South African Rand"

# Cryptocurrencies
eth = "Ethereum"
btc = "Bitcoin"
req = "Request Network"
iot = "Iota"
edo = "Eidoo"
bch = "Bitcoin Cash"
xrp = "Ripple"
xmr = "Monero"
omg = "OmiseGO"
ada = Cardano
lend = "ETHLend"
storj = "Storj"
LUN = "Lunyr"


# Coins that need additional information
[coins.xrb]
long_name = "RaiBlocks"
coinmarketcap = "raiblocks"

[coins.gnt]
long_name = "Golem Network Token"
coinmarketcap = "golem"

[coins.qash]
long_name = "QASH"
bitfinex = "QSH"
